Repository sksat/github-webhook-rs, pull requests merged in 2023-05, with the labels that each got.

#38 ビルド手続きの分離 / 変換アルゴリズム改良
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  dts-downloader/Cargo.toml
  dts-downloader/src/lib.rs
  github-webhook/Cargo.toml
  github-webhook/build.rs
  github-webhook/src/payload_types.rs
  type-generator/Cargo.toml
  type-generator/src/case.rs
  type-generator/src/dag.rs
  type-generator/src/frontend.rs
  type-generator/src/frontend/merge_union_type_lits.rs
  type-generator/src/frontend/name_types.rs
  type-generator/src/ir.rs
  type-generator/src/lib.rs
  type-generator/src/main.rs
  type-generator/src/to_tokens.rs
  type-generator/src/transformer.rs
  type-generator/src/transformer/borrow.rs
  type-generator/src/transformer/flatten_type.rs
  type-generator/src/transformer/internal_tag.rs
  type-generator/src/transformer/rename_all.rs
  type-generator/src/transformer/retype.rs
Labels: enhancement

#46 Add Renovate dry-run CI
  .github/workflows/validate-renovate.yml
Labels: enhancement

#47 Renovate octokit/webhooks version
  renovate.json
Labels: enhancement

#49 Enable Renovate config migration
  renovate.json
Labels: enhancement

#51 Fix Renovate octokit/webhooks
  renovate.json
Labels: bug

#54 Add missing license file
  LICENSE
Labels: documentation, enhancement

#58 Use dtolnay/rust-toolchain action instead of actions-rs/toolchain
  .github/workflows/rust.yml
Labels: enhancement

#60 Add rustdoc build job
  .github/workflows/rust.yml
Labels: documentation, enhancement

#61 Add README
  README.md
  github-webhook/Cargo.toml
Labels: documentation, enhancement

#65 Combine deps crate version
  Cargo.lock
  Cargo.toml
  dts-downloader/Cargo.toml
  github-webhook/Cargo.toml
  type-generator/Cargo.toml
Labels: enhancement

#66 Add release script
  release.sh
Labels: enhancement

#67 Config octokit/webhooks version as cargo metadata
  Cargo.lock
  dts-downloader/src/lib.rs
  github-webhook/Cargo.toml
  github-webhook/build.rs
  renovate.json
Labels: enhancement

#77 Add test by octokit/webhooks payload-example
  Cargo.lock
  github-webhook/Cargo.toml
  github-webhook/tests/parse-payload-example.rs
Labels: enhancement

#81 Add semver check CI job
  .github/workflows/rust.yml
Labels: enhancement
